#!/bin/bash

options=(
  style=round
  width=8.0
  hidpi=on
  background_color=0x1805030b
  inactive_color="gradient(top_left=0x88432253,bottom_right=0x881b1030)"
  active_color="gradient(top_left=0xff22d3ee,bottom_right=0xffff4fa3)"
)

borders "${options[@]}"
