### ref: https://qiita.com/vochicong/items/f20afc89a6847cd58f0f

### Install directory that using installer file
cask_args appdir: "/Applications"

### Main
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "homebrew/core"
tap "sanemat/font"
tap "aws/tap"
tap "fujiwara/tap"

### Install command line tools
#brew "automake"
brew "anyenv"
brew "ansible"
brew "awscli"
brew "aws-sam-cli"
brew "aws-sam-cli-beta-cdk"
brew "aws-vault"
brew "bat"
brew "blueutil"
brew "bitwarden-cli"
brew "bzip2"
brew "circleci"
brew "cli53"
brew "coreutils"
brew "direnv"
brew "envchain"
brew "exa"
brew "fcgi"
brew "fontforge"
brew "gh"
brew "ghq"
brew "gnutls"
brew "grep"
brew "gron"
brew "htop"
brew "hub"
brew "jq"
brew "lambroll"
brew "nmap"
brew "mysql"
brew "peco"
brew "php"  # for Alfred plugins
brew "pkg-config"
brew "pwgen"
brew "redis"
brew "s3cmd"
brew "saml2aws"
brew "shellcheck"
brew "sleepwatcher"
brew "tig"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh"
brew "zsh-completions"

### Install fonts
cask "font-ricty-diminished"
brew "sanemat/font/ricty"

### Install desktop applications
cask "authy"
cask "google-japanese-ime"
cask "google-chrome"
cask "notion"
cask "slack"
cask "visual-studio-code"

### Only macOS
if OS.mac?
  #cask "alfred"
  cask "bitwarden"
  cask "docker"
  cask "dbeaver-community"
  cask "firefox"
  cask "font-hack-nerd-font"
  cask "gather"
  cask "karabiner-elements"
  cask "iterm2"
  cask "macvim"
  cask "microsoft-remote-desktop"
  cask "postman"
  cask "rambox"
  cask "rectangle"
  cask "sequel-ace"
  cask "session-manager-plugin"
  cask "skitch"
  cask "the-unarchiver"
  cask "xquartz"
  cask "vnc-viewer"
#elseif OS.linux?
end

