## require
require 'fileutils'

### Install directory that using installer files
cask_args appdir: "/Applications"

### Tap list
tap_list = [
  "inamuu/tap",
  "FelixKratz/formulae",
  "dotenvx/brew",
  "fluxcd/tap",
  "fluxcd/tap",
  "fujiwara/tap",
  "future-architect/tap",
  "hashicorp/tap",
  "nikitabobko/tap",
  "sanemat/font",
  "idoavrah/homebrew",
]

for i in tap_list
  tap i
end

### Brew list
brew_list = [
  "act",
  "actionlint",
  "ansible",
  "anyenv",
  "argo",
  "aws-sam-cli",
  "aws-vault",
  "aws2-wrap",
  "awscli",
  "awslogs",
  "bash-language-server",
  "bat",
  "bitwarden-cli",
  "blueutil",
  "borders",
  "bzip2",
  "circleci",
  "cli53",
  "colordiff",
  "coreutils",
  "direnv",
  "dotenvx/brew/dotenvx",
  "easy-rsa",
  "eksctl",
  "envchain",
  "eza",
  "fcgi",
  "fontforge",
  "future-architect/tap/tftarget",
  "fzf",
  "gawk",
  "gh",
  "ghostscript",
  "ghq",
  "ghr",
  "git-delta",
  "gitui",
  "gnutls",
  "go-task",
  "gpg",
  "graphviz",
  "grep",
  "gron",
  "gsed",
  "hadolint",
  "helix",
  "helm",
  "helmfile",
  "htop",
  "httping",
  "hub",
  "jless",
  "jnv",
  "jq",
  "k9s",
  "kind",
  "kube-linter",
  "kubectl",
  "kubectx",
  "lambroll",
  "lazygit",
  "minikube",
  "mise",
  "mysql",
  "mysql@8.0",
  "nmap",
  "nvim",
  "peco",
  "percona-toolkit",
  "pinentry-mac",
  "pipx",
  "pkg-config",
  "putty",
  "pwgen",
  "pygments",
  "rclone",
  "redis",
  "ripgrep",
  "s3cmd",
  "saml2aws",
  "shellcheck",
  "sleepwatcher",
  "starship",
  "stern",
  "telnet",
  "terraform-ls",
  "terraformer",
  "tflint",
  "tftui",
  "tfz",
  "tig",
  "tmux",
  "tree",
  "uv",
  "vegeta",
  "watch",
  "wget",
  "yq",
  "zsh",
  "zsh-autosuggestions",
  "zsh-completions",
  "zsh-syntax-highlighting",
  "zx"
]

for i in brew_list
  brew i
end

### Install fonts
#cask "font-ricty-diminished"
#brew "sanemat/font/ricty"
#cask "font-udev-gothic"
#cask "font-udev-gothic-nf"


### Install desktop applications for macOS and Linux

#   "google-chrome",
#   "google-japanese-ime",
#   "tunnelblick",
cask_list = [
  "alt-tab",
  "codex",
  "kiro-cli",
  #"cursor",
  "font-udev-gothic",
  "font-udev-gothic-nf",
  "gcloud-cli",
  #"notion",
  "obsidian",
  "rar",
  "raycast",
  "slack",
  "visual-studio-code",
  "wezterm"
]

for i in cask_list
  cask i
end

### Install desktop apps only macOS for private and work
if OS.mac?
  #"alfred"
  #"zoom" インストール時にエラーになるため
  cask_list = [
    "aerospace",
    #"alacritty",
    "bitwarden",
    "dbeaver-community",
    #"docker",
    "firefox",
    "font-hack-nerd-font",
    "hammerspoon",
    #"iterm2",
    "karabiner-elements",
    #"macvim-app",
    #"postman",
    #"rectangle",
    "session-manager-plugin",
    "the-unarchiver",
    #"xquartz"
  ]
  for i in cask_list
    cask i
  end
end

### Install desktop apps only private and macOS
if ENV['PCENV'] == 'private' and OS.mac?
  cask "vnc-viewer"
  cask "rambox"
end

### Alacritty theme
#repository_url = "https://github.com/eendroroy/alacritty-theme.git"
#clone_dir = File.expand_path("~/.alacritty-colorshme")
#
#unless File.directory?(clone_dir)
#  system("git clone #{repository_url} #{clone_dir}")
#end
